name: "plot_upset"
description: "Generates UpSet plots to visualize the intersection of variant calls (FP, FN, TP) across different tools."
keywords:
  - plot
  - upset
  - benchmarking
  - intersection
  - variants
  - python
  - pandas
  - matplotlib
tools:
  - python:
      description: "Python programming language"
      homepage: "https://www.python.org"
      licence: ["Python-2.0"]
  - upsetplot:
      description: "A Python implementation of UpSet plots for visualizing intersecting sets."
      homepage: "https://upsetplot.readthedocs.io/"
      licence: ["BSD-3-Clause"]
  - pandas:
      description: "Data manipulation and analysis library for Python"
      homepage: "https://pandas.pydata.org/"
      licence: ["BSD-3-Clause"]
  - matplotlib:
      description: "Library for creating static, animated, and interactive visualizations in Python"
      homepage: "https://matplotlib.org/"
      licence: ["PSF-2.0"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information.
          Must contain `id` which matches the prefixes of the input files.
          e.g. `[ id:'test' ]`
    - files:
        type: list
        description: A list of CSV files (FP, FN, TP_base, TP_comp) generated by benchmarking tools.
        pattern: "*.csv"

output:
  - plot:
      - meta:
          type: map
          description: Groovy Map containing sample information.
      - png:
          type: file
          description: UpSet plots in PNG format (e.g., test_tp_fn_mqc.png and test_tp_fp_mqc.png).
          pattern: "*.png"

topics:
  - versions:
      - versions_python:
          type: string
          description: "The python version string emitted via Nextflow topics."

authors:
  - "@kubranarci"
maintainers:
  - "@kubranarci"