name: "cnv_benchmark"
description: "Subworkflow to benchmark copy number variations using Truvari, RTG Tools, or Wittyer."
keywords:
  - benchmark
  - copy number variants
  - truvari
  - rtgtools
  - wittyer
components:
  - truvari/bench
  - rtgtools/cnveval
  - local/wittyer_benchmark
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information.
    - test_vcf:
        type: file
        description: Query VCF file to be benchmarked.
        pattern: "*.{vcf.gz,vcf}"
    - test_index:
        type: file
        description: Index for the Query VCF.
        pattern: "*.{tbi,csi}"
    - truth_vcf:
        type: file
        description: Truth VCF file to benchmark against.
        pattern: "*.{vcf.gz,vcf}"
    - truth_index:
        type: file
        description: Index for the Truth VCF.
        pattern: "*.{tbi,csi}"
    - regionsbed:
        type: file
        description: Optional BED file containing regions to restrict the analysis to.
    - targets_bed:
        type: file
        description: Optional BED file containing target regions.
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fasta:
        type: file
        description: Reference genome FASTA file.
        pattern: "*.{fa,fasta}"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fai:
        type: file
        description: Reference genome FASTA index file.
        pattern: "*.fai"
output:
  tagged_variants:
    - meta:
        type: map
        description: Groovy Map containing variant tag information (FN, FP, TP_base, TP_comp).
    - vcfs:
        type: file
        description: VCF files containing specific variant classifications from the chosen tool.
        pattern: "*.vcf.gz"
  summary_reports:
    - meta:
        type: map
        description: Groovy Map containing report information.
    - reports:
        type: file
        description: Summary reports generated by the chosen benchmarking tool.
  logs:
    - meta:
        type: map
        description: Groovy Map containing log information.
    - log:
        type: file
        description: Log files generated by the tools.
        pattern: "*.txt"
authors:
  - "@kubranarci"
maintainers:
  - "@kubranarci"
