lint:
  files_unchanged:
    - .gitignore
    - docs/images/nf-core-variantbenchmarking_logo_dark.png
    - docs/images/nf-core-variantbenchmarking_logo_light.png
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: kuebra.narci@dkfz-heidelberg.de
  description: "Variant Benchmarking pipeline for germline and somatic variant callers "
  force: false
  is_nfcore: true
  name: variantbenchmarking
  org: nf-core
  outdir: .
  version: 1.2.0
