name: "small_germline_benchmark"
description: "Subworkflow to benchmark small germline variants using RTG Tools or Happy."
keywords:
  - benchmark
  - germline
  - rtgtools
  - happy
  - variants
components:
  - rtgtools/vcfeval
  - local/happy_benchmark
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information.
    - test_vcf:
        type: file
        description: Query VCF file to be benchmarked.
        pattern: "*.{vcf.gz,vcf}"
    - test_index:
        type: file
        description: Index for the Query VCF.
        pattern: "*.{tbi,csi}"
    - truth_vcf:
        type: file
        description: Truth VCF file to benchmark against.
        pattern: "*.{vcf.gz,vcf}"
    - truth_index:
        type: file
        description: Index for the Truth VCF.
        pattern: "*.{tbi,csi}"
    - regionsbed:
        type: file
        description: Optional BED file containing regions to restrict the analysis to.
    - targetsbed:
        type: file
        description: Optional BED file containing target regions.
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fasta:
        type: file
        description: Reference genome FASTA file.
        pattern: "*.{fa,fasta}"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fai:
        type: file
        description: Reference genome FASTA index file.
        pattern: "*.fai"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - sdf:
        type: directory
        description: Reference genome directory required by RTG Tools.
  - - meta:
        type: map
        description: Groovy Map containing bed information.
    - falsepositive_bed:
        type: file
        description: Optional BED file of false positive regions.
  - - meta:
        type: map
        description: Groovy Map containing bed information.
    - stratification_bed:
        type: file
        description: Optional BED file for stratification.
  - - meta:
        type: map
        description: Groovy Map containing TSV information.
    - stratification_tsv:
        type: file
        description: TSV file listing stratification regions.
output:
  summary_reports:
      - meta:
          type: map
          description: Groovy Map containing report information.
      - reports:
          type: file
          description: Summary reports generated by the benchmarking tool.
  tagged_variants:
      - meta:
          type: map
          description: Groovy Map containing variant tag information.
      - vcfs:
          type: file
          description: Filtered VCF files containing specific variant classifications.
          pattern: "*.vcf.gz"
authors:
  - "@kubranarci"
maintainers:
  - "@kubranarci"