name: "small_germline_benchmark"
description: "Subworkflow to benchmark small germline variants using RTG Tools or Happy."
keywords:
  - benchmark
  - germline
  - rtgtools
  - happy
  - variants
components:
  - rtgtools/vcfeval
  - local/happy_benchmark
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information.
    - test_vcf:
        type: file
        description: Query VCF file to be benchmarked.
        pattern: "*.vcf.gz"
    - test_index:
        type: file
        description: Index for the Query VCF.
        pattern: "*.tbi"
    - truth_vcf:
        type: file
        description: Truth VCF file to benchmark against.
        pattern: "*.vcf.gz"
    - truth_index:
        type: file
        description: Index for the Truth VCF.
        pattern: "*.tbi"
    - regionsbed:
        type: file
        description: Optional BED file containing regions to restrict the analysis to.
    - targetsbed:
        type: file
        description: Optional BED file containing target regions.
        pattern: "*.bed"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fasta:
        type: file
        description: Reference genome FASTA file.
        pattern: "*.{fa,fasta}"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fai:
        type: file
        description: Reference genome FASTA index file.
        pattern: "*.fai"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - sdf:
        type: directory
        description: Reference genome directory required by RTG Tools.
        pattern: "*.sdf"
  - - meta:
        type: map
        description: Groovy Map containing bed information.
    - high_confidence_bed:
        type: file
        description: Optional BED file of high confidence regions.
        pattern: "*.bed"
  - - meta:
        type: map
        description: Groovy Map containing bed information.
    - stratification_bed:
        type: file
        description: Optional BED file for stratification.
        pattern: "*.bed"
  - - meta:
        type: map
        description: Groovy Map containing TSV information.
    - stratification_tsv:
        type: file
        description: TSV file listing stratification regions.
        pattern: "*.tsv"
output:
  summary_reports:
    - meta:
        type: map
        description: Groovy Map containing report information.
    - reports:
        type: file
        description: Summary reports generated by the benchmarking tool.
        pattern: "*.{txt,json}"
  tagged_variants:
    - meta:
        type: map
        description: Groovy Map containing variant tag information.
    - vcfs:
        type: file
        description: Filtered VCF files containing specific variant classifications.
        pattern: "*.vcf.gz"
authors:
  - "@kubranarci"
maintainers:
  - "@kubranarci"
