datasets:
  report:
    path: CSVPATH #rtgtools.sv.summary.csv
    separator: ","
views:
  test:
    dataset: report
    render-table:
      columns:
        Tool:
          display-mode: normal
        Threshold:
          display-mode: normal
        TP_base:
          display-mode: normal
        FN:
          display-mode: normal
        TP_call:
          display-mode: normal
        FP:
          display-mode: normal
        Precision:
          display-mode: normal
        Recall:
          display-mode: normal
        F1:
          display-mode: normal
# Tool,Threshold,TP_base,TP_call,FP,FN,Precision,Recall,F1
