name: "svanalyzer_benchmark"
description: "Subworkflow to benchmark structural variants against a truth set using SVAnalyzer and subtract local modules."
keywords:
  - benchmark
  - svanalyzer
  - structural variants
  - vcf
components:
  - svanalyzer/svbenchmark
  - local/custom/subtract_vcf
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information.
    - test_vcf:
        type: file
        description: Query VCF file to be benchmarked.
        pattern: "*.{vcf.gz,vcf}"
    - test_index:
        type: file
        description: Index for the Query VCF.
        pattern: "*.{tbi,csi}"
    - truth_vcf:
        type: file
        description: Truth VCF file to benchmark against.
        pattern: "*.{vcf.gz,vcf}"
    - truth_index:
        type: file
        description: Index for the Truth VCF.
        pattern: "*.{tbi,csi}"
    - regionsbed:
        type: file
        description: Optional BED file containing regions to restrict the analysis to.
    - targets_bed:
        type: file
        description: Optional BED file containing target regions.
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fasta:
        type: file
        description: Reference genome FASTA file.
        pattern: "*.{fa,fasta}"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fai:
        type: file
        description: Reference genome FASTA index file.
        pattern: "*.fai"
output:
  tagged_variants:
      - meta:
          type: map
          description: Groovy Map containing variant tag information (FN, FP, TP_comp, TP_base).
      - vcfs:
          type: file
          description: Filtered VCF files containing specific variant classifications.
          pattern: "*.vcf.gz"
  report:
      - meta:
          type: map
          description: Groovy Map containing report information.
      - reports:
          type: file
          description: Summary report generated by SVAnalyzer.
          pattern: "*.report"
authors:
  - "@kubranarci"
maintainers:
  - "@kubranarci"