name: "sv_benchmark"
description: "Subworkflow to benchmark structural germline variants using Truvari, SVAnalyzer, or Wittyer."
keywords:
  - benchmark
  - structural variants
  - truvari
  - svanalyzer
  - wittyer
components:
  - truvari/bench
  - local/svanalyzer_benchmark
  - local/wittyer_benchmark
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information.
    - test_vcf:
        type: file
        description: Query VCF file to be benchmarked.
        pattern: "*.vcf.gz"
    - test_index:
        type: file
        description: Index for the Query VCF.
        pattern: "*.tbi"
    - truth_vcf:
        type: file
        description: Truth VCF file to benchmark against.
        pattern: "*.vcf.gz"
    - truth_index:
        type: file
        description: Index for the Truth VCF.
        pattern: "*.tbi"
    - regionsbed:
        type: file
        description: Optional BED file containing regions to restrict the analysis to.
        pattern: "*.bed"
    - targets_bed:
        type: file
        description: Optional BED file containing target regions.
        pattern: "*.bed"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fasta:
        type: file
        description: Reference genome FASTA file.
        pattern: "*.{fa,fasta}"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fai:
        type: file
        description: Reference genome FASTA index file.
        pattern: "*.fai"
output:
  tagged_variants:
    - meta:
        type: map
        description: Groovy Map containing variant tag information (FN, FP, TP_base, TP_comp).
    - vcfs:
        type: file
        description: VCF files containing specific variant classifications from the chosen tool.
        pattern: "*.vcf.gz"
  summary_reports:
    - meta:
        type: map
        description: Groovy Map containing report information.
    - reports:
        type: file
        description: Summary reports generated by the chosen benchmarking tool.
        pattern: "*.{json,report}"
  logs:
    - log:
        type: file
        description: Log files generated by the tools (e.g., Truvari logs).
        pattern: "*.txt"
authors:
  - "@kubranarci"
maintainers:
  - "@kubranarci"
