name: "concordance_analysis"
description: "Subworkflow for concordance analysis between base and test VCFs using GATK4 and BCFtools."
keywords:
  - gatk4
  - concordance
  - bcftools
  - benchmark
  - variants
components:
  - gatk4/concordance
  - bcftools/view
  - bcftools/reheader
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information.
    - vcf:
        type: file
        description: VCF files to be compared.
        pattern: "*.vcf.gz"
    - tbi:
        type: file
        description: Index for the VCF files.
        pattern: "*.tbi"
  - - bed:
        type: file
        description: Optional BED file containing evaluation regions.
        pattern: "*.bed"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fasta:
        type: file
        description: Reference genome FASTA file.
        pattern: "*.{fa,fasta}"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fai:
        type: file
        description: Reference genome FASTA index file.
        pattern: "*.fai"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - dictionary:
        type: file
        description: Reference genome dictionary file.
        pattern: "*.dict"
output:
  summary_reports:
    - meta:
        type: map
        description: Groovy Map containing report information.
    - reports:
        type: file
        description: Summary reports generated by GATK4 Concordance.
        pattern: "*.txt"
  tagged_variants:
    - meta:
        type: map
        description: Groovy Map containing variant tag information.
    - vcfs:
        type: file
        description: Split and reheaded VCF files containing TP, FP, and FN variants.
        pattern: "*.vcf.gz"
authors:
  - "@kubranarci"
maintainers:
  - "@kubranarci"
