name: "small_somatic_benchmark"
description: "Subworkflow to benchmark small somatic variants using Sompy or RTG Tools."
keywords:
  - benchmark
  - somatic
  - sompy
  - rtgtools
  - variants
components:
  - local/sompy_benchmark
  - rtgtools/vcfeval
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information.
    - test_vcf:
        type: file
        description: Query VCF file to be benchmarked.
        pattern: "*.vcf.gz"
    - test_index:
        type: file
        description: Index for the Query VCF.
        pattern: "*.tbi"
    - truth_vcf:
        type: file
        description: Truth VCF file to benchmark against.
        pattern: "*.vcf.gz"
    - truth_index:
        type: file
        description: Index for the Truth VCF.
        pattern: "*.tbi"
    - regionsbed:
        type: file
        description: Optional BED file containing regions to restrict the analysis to.
        pattern: "*.bed"
    - targets_bed:
        type: file
        description: Optional BED file containing target regions.
        pattern: "*.bed"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fasta:
        type: file
        description: Reference genome FASTA file.
        pattern: "*.{fa,fasta}"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - fai:
        type: file
        description: Reference genome FASTA index file.
        pattern: "*.fai"
  - - meta:
        type: map
        description: Groovy Map containing reference information.
    - sdf:
        type: directory
        description: Reference genome SDF directory required by RTG Tools.
        pattern: "*.sdf"
  - - meta:
        type: map
        description: Groovy Map containing bed information.
    - falsepositive_bed:
        type: file
        description: Optional BED file of false positive regions.
        pattern: "*.bed"
  - - meta:
        type: map
        description: Groovy Map containing bed information.
    - ambiguous_beds:
        type: file
        description: Optional BED file of ambiguous regions.
        pattern: "*.bed"
output:
  summary_reports:
    - meta:
        type: map
        description: Groovy Map containing report information.
    - reports:
        type: file
        description: Summary reports generated by Sompy or RTG Tools.
        pattern: "*.{json,txt}"
  tagged_variants:
    - meta:
        type: map
        description: Groovy Map containing variant tag information.
    - vcfs:
        type: file
        description: Filtered VCF files containing specific variant classifications from RTG Tools.
        pattern: "*.vcf.gz"
  tagged_variants_csv:
    - meta:
        type: map
        description: Groovy Map containing variant tag information.
    - csvs:
        type: file
        description: CSV files containing tagged variants from Sompy.
        pattern: "*.csv"
authors:
  - "@kubranarci"
maintainers:
  - "@kubranarci"
