# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "WITTYER_BENCHMARK"
description: Benchmarking structural variants using Wittyer
keywords:
  - benchmark
  - wittyer
  - structural variants
  - vcf
components:
  - tabix/bgzip
  - wittyer
input:
  - input_ch:
      description: Channel containing target and truth VCF files with regions
      structure:
        - meta:
          type: map
          description: Metadata map
        - test_vcf:
          type: file
          description: Query VCF file
          pattern: "*.{vcf,vcf.gz}"
        - test_index:
          type: file
          description: Query VCF index file
          pattern: "*.{tbi,csi}"
        - truth_vcf:
          type: file
          description: Truth VCF file
          pattern: "*.{vcf,vcf.gz}"
        - truth_index:
          type: file
          description: Truth VCF index file
          pattern: "*.{tbi,csi}"
        - regionsbed:
          type: file
          description: BED file containing regions to evaluate
          pattern: "*.bed"
        - targets_bed:
          type: file
          description: BED file containing target regions
          pattern: "*.bed"
output:
  - report:
      description: Channel containing the grouped benchmarking reports
      structure:
        - meta:
          type: map
          description: Metadata map containing variant type and tool name
        - reports:
          type: list
          description: List of report files generated by Wittyer
          pattern: "*.json"
authors:
  - "@kubranarci"
maintainers:
  - "@kubranarci"