%%metro title: nf-core/variantbenchmarking Pipeline
%%metro style: dark
%%metro nodeSpacing: 2000
%%metro rankSpacing: 1500
%%metro legend: bl
%%metro compact_offsets: true
%%metro file: ref_genome_file | FASTA
%%metro file: truth_vcf_file | VCF
%%metro file: regions_bed_file | BED
%%metro file: targets_bed_file | BED
%%metro file: samplesheet_file | TSV
%%metro file: snv_stats_out | TSV
%%metro file: sv_stats_out | TSV
%%metro file: html_out | HTML
%%metro file: multiqc_out | YML
%%metro file: plots_out | PNG
%%metro file: merged_csv | CSV
%%metro file: bench_sum | TXT


%% Define Metro Lines
%%metro line: truth | Truth Preprocessing | #4CAF50
%%metro line: test| Test Preprocessing | #ff9800
%%metro line: sv_cnv | SV/CNV Benchmarking | #F44336
%%metro line: snv_indel | SNV/INDEL Benchmarking | #f321cd
%%metro line: concordance | Concordance Analysis| #da630e
%%metro line: intersection | Intersection Analysis | #da930e
%%metro line: output | Output Processing | #03A9F4

graph LR

    subgraph SG1_Inputs [Inputs]
        %%metro direction: LR
        ref_genome_file[ ]
        ref_genome[Reference Genome]
        truth_vcf_file[ ]
        truth_vcf[Truth VCF]
        regions_bed_file[ ]
        regions_bed[Regions BED]
        targets_bed_file[ ]
        targets_bed[Targets BED]
        samplesheet_file[ ]
        samplesheet[Samplesheet]
        _inputs_hub[hidden]

        ref_genome_file -->|truth| ref_genome
        truth_vcf_file -->|truth| truth_vcf
        regions_bed_file -->|truth| regions_bed
        targets_bed_file -->|truth| targets_bed
        samplesheet_file -->|test| samplesheet
        ref_genome -->|truth| _inputs_hub
        truth_vcf -->|truth| _inputs_hub
        regions_bed -->|truth| _inputs_hub
        targets_bed -->|truth| _inputs_hub
        samplesheet -->|test| _inputs_hub
    end

    subgraph SG2_Preproc [Preprocessing (Optional)]
        %%metro direction: LR
        %%metro entry: left | truth, test
        %%metro exit: right | truth, test
        Liftover((Liftover (picard, UCSC)))
        Subsample (bcftools view)
        Subsample -->|test,truth| Liftover
    end

    subgraph SG23_SVprocess [SV Processing (Optional)]
        %%metro entry: left | test
        %%metro exit: right | test
        %%metro exit: bottom | truth
        SVProcess((SV Processing))
        Liftover -->|test| SVProcess
    end

    subgraph SG23_Norm [Variant Normalization (Optional)]
        %%metro entry: left | test
        %%metro exit: right | test
        %%metro exit: bottom | truth
        Norm((Variant Normalization))
        SVProcess -->|test| Norm
        Liftover -->|truth| Norm
    end

    subgraph SG2e_Filter [Variant Filtering (Optional)]
        %%metro entry: left | truth, test
        %%metro exit: right | truth, test
        Filterbcftools((bcftools filter))
        SURVIVORFilter(SURVIVOR filter)
        FilterContigs((filter contigs))
        _h1[hidden]
        Norm -->|test| FilterContigs
        FilterContigs -->|test| Filterbcftools
        FilterContigs -->|test| SURVIVORFilter
        Norm -->|truth,test| _h1

    end
    _h2[hidden2]
    _h1 -->|truth,test| _h2

    subgraph SG2e_Stats [Variant Statistics]
        %%metro entry: left | truth, test
        %%metro exit: right | truth, test
        VariantStats1((SNV stats))
        VariantStats2((SV stats))
        bcftoolsStats((bcftools stats))
        SURVIVORStats((SURVIVOR stats))
        snv_stats_out[ ]
        sv_stats_out[ ]
        bcftoolsStats -->|test,truth| VariantStats1
        SURVIVORStats -->|test,truth| VariantStats2
        VariantStats1 -->|output| snv_stats_out
        VariantStats2 -->|output| sv_stats_out
    end

    subgraph SG2d_Ensemble [Ensemble Truth (Optional - to generate a proxy truth)]
        %%metro entry: left | test
        %%metro exit: right | truth

        EnsembleMerge1((bcftools merge))
        EnsembleMerge2((SURVIVOR merge))
        Consensus((Consensus Filter))
        %% Internal connections
        EnsembleMerge1 -->|test| Consensus
        EnsembleMerge2 -->|test| Consensus
    end

    subgraph SG3_Benchmarking [Benchmarking]
        %%metro direction: LR
        BenchHub((BENCHMARKING))
        Truvari((Truvari))
        RTGvcfeval((RTGtools vcfeval))
        SVanalyzer((SVanalyzer))
        RTGbndeval((RTGtools bndeval))
        happy((hap.py))
        Wittyer((wittyer))
        sompy((som.py))
        Intersection((Intersection))
        GATK4Conc((GATK4 Concordance))

        %% Hub to Tools connections
        BenchHub -->|sv_cnv| Truvari
        BenchHub -->|snv_indel| RTGvcfeval
        BenchHub -->|sv_cnv| SVanalyzer
        BenchHub -->|sv_cnv| RTGbndeval
        BenchHub -->|snv_indel| happy
        BenchHub -->|sv_cnv| Wittyer
        BenchHub -->|snv_indel| sompy
        BenchHub -->|intersection| Intersection
        BenchHub -->|concordance| GATK4Conc
    end

    subgraph SG4_Outputs [Output Processing]
        %%metro direction: LR
        ResultsHub((RESULTS))
        MergeRes((Merge TP/FP/FN results))
        VCF2CSV((VCF to CSV))
        SumStats((Summary TP/FP/FN Stats))
        Plots((Plots))
        datavzrd(datavzrd)
        MergedCSVs[Merged CSVs]
        BenchSummaries[Benchmarking Summaries]
        HTMLReport[HTML Report]
        MultiQC[MultiQC Report]
        html_out[ ]
        multiqc_out[ ]
        plots_out[ ]
        merged_csv[ ]
        bench_sum[ ]

        %% Internal Processing connections
        ResultsHub -->|output| MergeRes
        MergeRes -->|output| VCF2CSV
        ResultsHub -->|output| SumStats
        SumStats -->|output| Plots
        SumStats -->|output| datavzrd
        VCF2CSV -->|output| Plots

        %% Final Files connections
        VCF2CSV -->|output| MergedCSVs
        MergedCSVs -->|output|merged_csv
        ResultsHub -->|output| BenchSummaries
        BenchSummaries -->|output|bench_sum
        datavzrd -->|output| HTMLReport
        HTMLReport -->|output|html_out
        SumStats -->|output| MultiQC
        BenchSummaries -->|output| MultiQC
        Plots -->|output| MultiQC
        Plots -->|output|plots_out
        MultiQC -->|output|multiqc_out

    end

    %% SG1 -> SG2
    _inputs_hub -->|truth| Liftover
    _inputs_hub -->|test| Liftover
    _inputs_hub -->|test| Subsample
    _inputs_hub -->|test| SVProcess
    _inputs_hub -->|truth,test| Norm

    %% SG2 Internal Crossings
    Liftover -->|test| SVProcess
    Liftover -->|truth| Norm

    %% Test to Ensemble & Stats
    Filterbcftools -->|test| EnsembleMerge1
    SURVIVORFilter -->|test| EnsembleMerge2

    Filterbcftools -->|test| bcftoolsStats
    SURVIVORFilter -->|test| SURVIVORStats
    _h1 -->|truth| bcftoolsStats
    _h1 -->|truth| SURVIVORStats

    %% SG2 -> SG3 (Connecting track ends to Shared Stats)
    _h2 -->|test| BenchHub
    _h2 -->|truth| BenchHub
    Consensus -->|truth| BenchHub

    %% SG3 -> SG4 (Connecting tools to Results Hub)
    Truvari -->|sv_cnv| ResultsHub
    RTGvcfeval -->|snv_indel| ResultsHub
    SVanalyzer -->|sv_cnv| ResultsHub
    RTGbndeval -->|sv_cnv| ResultsHub
    happy -->|snv_indel| ResultsHub
    Wittyer -->|sv_cnv| ResultsHub
    sompy -->|snv_indel| ResultsHub
    Intersection -->|intersection| ResultsHub
    GATK4Conc -->|concordance| ResultsHub
